pipeline:
  identifier: Build_gosample_1742297366721
  name: Build gosample
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1742223495982
        repoName: gosample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_go_app
                  name: Build Go App
                  spec:
                    connectorRef: account.harnessImage
                    image: harness/delegate:25.02.85300
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: gke
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
        delegateSelectors:
          - kubernetes-delegate
